[project]
name = "2024-10_desy_ltp-el_analysis"
version = "0.1.0"
description = ""
authors = [
    {name = "Clemens Prescher",email = "clemens.prescher@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12, <3.14"
dependencies = [
    "dioptas (>=0.7.1,<0.8.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
